/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: 'doc',
      id: 'introduction',
    },
    {
      type: 'doc',
      id: 'get_started',
    },
    {
      type: 'doc',
      id: 'tech_overview',
    },
    {
      type: 'category',
      label: 'Integration',
      items: [
        {
          type: 'doc',
          id: 'Apis/following_list',
        },
        {
          type: 'doc',
          id: 'Apis/follow_button',
        },
        {
          type: 'doc',
          id: 'Apis/connect',
        },
        {
          type: 'doc',
          id: 'Apis/recommendation',
        },
        {
          type: 'doc',
          id: 'Apis/featured',
        },
        {
          type: 'doc',
          id: 'Apis/popular',
        },
        {
          type: 'doc',
          id: 'Apis/playground',
        },
      ],
    },
    {
      type: 'category',
      label: 'Partnership Examples',
      items: [
        {
          type: 'doc',
          id: 'Partnership Examples/unipass',
        },
        {
          type: 'doc',
          id: 'Partnership Examples/treasureland',
        },
        {
          type: 'doc',
          id: 'Partnership Examples/convo',
        },
      ],
    },
    {
      type: 'category',
      label: 'More Examples',
      items: [
        {
          type: 'doc',
          id: 'More Examples/dao',
        },
        {
          type: 'doc',
          id: 'More Examples/chat',
        },
        {
          type: 'doc',
          id: 'More Examples/nft_trading',
        },
        {
          type: 'doc',
          id: 'More Examples/did',
        },
        {
          type: 'doc',
          id: 'More Examples/feeds',
        },
        {
          type: 'doc',
          id: 'More Examples/games',
        },
        {
          type: 'doc',
          id: 'More Examples/blockchain_explorer',
        },
      ],
    },
    {
      type: 'category',
      label: 'Community',
      items: [
        {
          type: 'doc',
          id: 'Community/community',
        },
        {
          type: 'doc',
          id: 'Community/past_events',
        }
      ]
    },
    {
      type: 'doc',
      id: 'contact_us',
    },

  ],
  introductionSidebar: [

  ],
  integrationSidebar: [

  ],
  showcaseSidebar: [

  ],
  communitySidebar: [
    
  ]
   
};

module.exports = sidebars;
